<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KUHR709B" ignored="0" name="Command line test" tests="3" failures="1" timestamp="2022-05-21T15:14:26 CDT" time="17.154" errors="0">
  <testcase name="X" time="0.004" classname="scripts._01_AppleTest">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:50)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase name="testAppleTitle" time="0.846" classname="scripts._01_AppleTest"/>
  <testcase name="testAppleURL" time="0.834" classname="scripts._01_AppleTest"/>
</testsuite> <!-- Command line test -->
